### ISSUE TITLE
Blocklet Developer Docs: Samples 版块文档完善

### ISSUE THREAD

**Issue by linchen1987** [blocklet/blocklet-site#10]
## 呈现方式

- 所有的 Demo 都有豆腐块的方式展示出来，包含封面图、Store 链接、Repo 链接、文章链接
- 可以包含我们官方的 Demo，社区用户产生的 Demo

## 用户价值

1. 开发者可以通过 demo 卡片了解 blocklet 平台的能力
2. 开发者可以通过安装 demo 体验 blocklet 平台的功能
3. 开发者可以通过 demo 源码学习 blocklet 功能的实现方式

## Demo 文档

每个 Demo 的文档放在文档站下面：https://developer.blocklet.io/docs/samples/simple-html-demo ，这篇文章应该遵循如下的提纲：
- 为什么做这个 Demo？
- 展示了 Blocklet 平台哪些能力？
- 基本实现思路
- 关键代码解释
- 知识点文档链接：行文中就可以包括进去
- Store、Repo 链接

## 应该支持的 Demo 列表

> 这个列表纪要能展示我们的平台能力，也要能 cover 常见应用开发的需求：比如用户管理、权限管理、数据持久化

- [ ] 不同类型的 blocklet
	- [ ] static
	- [ ] dapp
	- [ ] group
- [ ] 展示 blocklet service 能力
	- [ ] auth：用户认证、权限控制
	- [ ] notification：给用户发通知，收发用户消息
- [ ] 展示可组合能力的
	- [ ] 组合前端：blocklet-ui
	- [ ] 组合控制台：blocklet-ui
	- [ ] 嵌套的组合
- [ ] 展示盈利能力的
	- [ ] 组件付费
	- [ ] 组合付费  
- [ ] 展示和链交互能力的
	- [ ] ethereum 链
	- [ ] ocap 链
- [ ] 展示 did-connect 能力的
	- [ ] 可以链接到 did-connect 站点
- [ ] 展示 nft 能力的
	- [ ] asset
	- [ ] factory
- [ ] 展示 xmark 能力的
	- [ ] pages
	- [ ] docs
- [ ] 展示主流框架支持能力的
	- [ ] react
	- [ ] vue

## 现有 Demo 列表

> 这个列表应该适配到上面的列表中去

- [ ] Simple HTML Demo: 最简单的 blocklet
- [ ] 2048 Demo: 将静态站点封装为 blocklet
- [ ] React Demo: 使用 react 开发 blocklet
- [ ] Blocklet Page Demo: 使用 blocklet page 开发 blocklet
- [ ] Auth Demo: 演示权限管理能力，Passport 使用
- [ ] Notification Demo: 演示 Blocklet 的通知能力
- [ ] Component Demo: 演示组合 Blocklet
- [ ] DID Connect Demo: 使用 DID Connect
- 更多的需要整理进来

**Comment by wangshijun** [comment]
related https://github.com/ArcBlock/xmark-next/issues/137

**Comment by wangshijun** [comment]
现有 Demo 都需要更新下，前置工作：

- 更新所有依赖到最新，确保能打包、发版
