### ISSUE TITLE
developer没有更新logo，按钮大小和主站的不一样，footer没有更新

### ISSUE THREAD

**Issue by dosthcool** [blocklet/blocklet-site#11]
<img width="623" alt="截屏2022-08-18 13 54 47" src="https://user-images.githubusercontent.com/24971257/185304533-374595c8-6fe1-4a1b-b4f0-5ae1d0177400.png">
<img width="635" alt="截屏2022-08-18 13 54 53" src="https://user-images.githubusercontent.com/24971257/185304544-e628b755-9270-46fb-bd87-d6b9a971e83a.png">

**Comment by linchen1987** [comment]
fixed
