### ISSUE TITLE
开发者文档首页优化

### ISSUE THREAD

**Issue by wangshijun** [blocklet/blocklet-site#16]
## 需求

来到文档首页的人，大部分可能是遇到了问题，我们把常见 Topic 列出来，再加上比较好的搜索支持，会更容易帮他们解决问题。

## 方案

站在开发者的角度去思考，他可能遇到哪些问题，把这些问题分类，组合成豆腐块，排列在首页。比如：开发、打包、发布、运营

- 开发阶段：如何初始化？如何管理用户？如果管理权限？如何做控制台？如何集成其他组件？如何持久化数据？如何和链交互？
- 打包阶段：Store 的要求？Logo、Screenshot、Readme，如何验证？如何作为子组件开发
- 发布阶段：如何定价？如何分成？
- 运维阶段：如何做 migration？如何升级？

## 参考

- https://developer.chrome.com/docs/webstore/
- https://www.gatsbyjs.com/docs

个人强烈建议参考的是 gatsby js，他的文档结构非常清晰：

- How-to guides：How
- Reference guides：Why
- Conceptual guides：What

并且层层递进：

![Screen Shot 2022-08-26 at 07 47 33](https://user-images.githubusercontent.com/719985/186788171-ef72da1c-07bd-4a88-b095-ea4040933bea.png)

![Screen Shot 2022-08-26 at 07 48 07](https://user-images.githubusercontent.com/719985/186788179-95646471-d623-467b-8693-4b80d5d9ae4a.png)

**Comment by wangshijun** [comment]
related https://github.com/ArcBlock/xmark-next/issues/137

**Comment by linchen1987** [comment]
https://github.com/ArcBlock/blocklet-server/issues/5370

**Comment by mave99a** [comment]
觉得这个项目的文档也做得结构很清晰，非常适合blocklet server 

https://tauri.app/v1/guides/getting-started/prerequisites

<img width="283" alt="image" src="https://user-images.githubusercontent.com/41923/188539902-9e3dc3f5-19e0-4aa7-9157-e2b7e29c252f.png">

**Comment by wangshijun** [comment]
v0.1.70 里面有显著的改进
