### ISSUE TITLE
20220826 Review 反馈

### ISSUE THREAD

**Issue by wangshijun** [blocklet/blocklet-site#17]
- [x] Blocklet Meta 就是 blocklet.yml，我们不需要造出两个概念来，所有使用 blocklet meta 的地方我们都改成 blocklet.yml
- [x] 所有可以链接的都应该加上链接，比如 create-blocklet，比如各种 blocklet cli 子命令
- [x] 访问入口通常情况下不需要用户配置

**Comment by wangshijun** [comment]
20220830 补充

- [ ] https://developer.blocklet.io/docs/zh/apis/blocklet-sdk 切换到中文了，但是显示的还是英文？
- [ ] Environments 里面没有介绍各个值/方法可以用来做什么？
- [ ] Environments 里面没有包括 mode？
- [ ] Middlewares 里面最好分开两组？分别介绍 user、auth？
- [ ] 整个 SDK 的右侧导航看着挺乱的，尤其是二级菜单的部分，比如 client 这个字眼可以去掉？

**Comment by linchen1987** [comment]
>  Environments 里面没有介绍各个值/方法可以用来做什么？

<img width="991" alt="image" src="https://user-images.githubusercontent.com/11010275/204183143-02148076-86a1-48ed-984e-2c1453fd5d82.png">

**Comment by linchen1987** [comment]
> Middlewares 里面最好分开两组？分别介绍 user、auth？

https://github.com/blocklet/blocklet-site/commit/d846a509d85ffac8daa5b017ebd263bec6cabc5e
