### ISSUE TITLE
developer doc review 反馈 0919

### ISSUE THREAD

**Issue by wangshijun** [blocklet/blocklet-site#27]
![Screen Shot 2022-09-19 at 11 50 57](https://user-images.githubusercontent.com/719985/190947060-a1c27046-9ec6-4836-b760-a8a43ecf6946.png)

- [x] Auth 的右侧导航显的太凌乱，api 签名不适合做标题，建议简化为函数名字或者函数用途

![Screen Shot 2022-09-19 at 12 01 52](https://user-images.githubusercontent.com/719985/190947938-5289ec9a-3ebe-44f4-b8e3-9531b4bbb359.png)

- [x] component api 需要解释，给出示例
- [x] environment 里面可以增加必要的解释
- [x] Conceptual guides > blocklet 里面需要增加 blocklet appId、blocklet Id 的解释
- [x] blocklet-spec 右侧边栏有些文本过长
- [x] blocklet cli 里面整个文档的 children 和 components 叫法不一致，我们干脆统一下？都叫 components？
- [x] known-issues 里面的第一个文不对题
- [x] sidebar 中英文都没有翻译？
- [x] meta.js 最好能贴个完整的，逐个字段解释下
- [x] 添加付费组件在 blocklet cli 里面还是不支持的？
- [x] blocklet ui 的包名字都是错的 @blocklet/ui
- [x] navigation、theme、copyright 不应该合并到一起，navigation 是组合型 blocklet 非常重要的话题，需要写的更细，比如如何写，结果是怎样的，自动合并逻辑
- [x] types 的解释也过于简略，相当于没有

**Comment by linchen1987** [comment]
> 添加付费组件在 blocklet cli 里面还是不支持的？

添加付费组件和添加免费组件的方式相同 `blocklet add`, `blocklet remove`

尚未支持开发带有付费组件的 blocklet
