### ISSUE TITLE
blocklet developer site 需要有个自己的 Logo

### ISSUE THREAD

**Issue by wangshijun** [blocklet/blocklet-site#4]
https://developer.blocklet.io/

**Comment by dosthcool** [comment]
<img width="931" alt="截屏2022-08-14 09 29 06" src="https://user-images.githubusercontent.com/24971257/184518766-98ac4d10-f750-416e-a266-c997ad240360.png">
是否需要app icon？
如果需要，那样式需要更改成和blocklet不同的icon。

**Comment by mave99a** [comment]
这样就可以了

**Comment by wangshijun** [comment]
> 这样就可以了

需要复数么？

**Comment by mave99a** [comment]
这里应该不需要复数

**Comment by mave99a** [comment]
站点可以叫 Blocklet Developer Portal

**Comment by wangshijun** [comment]
fixed in v0.1.11
