### ISSUE TITLE
[Feedback] blocklet server 每个页面里的上上下文帮助应该和文档站建立直接的联系

### ISSUE THREAD

**Issue by mave99a** [blocklet/blocklet-site#56]
blocklet server 每个页面里的上上下文帮助应该和文档站建立直接的联系。

包括这些地方：

上下文帮助：
<img width="301" alt="image" src="https://user-images.githubusercontent.com/41923/196011559-fa8a082d-8d5e-4b8d-b654-b36cc2831e9c.png">

首页的document 链接： 
<img width="519" alt="image" src="https://user-images.githubusercontent.com/41923/196011539-62f4a798-5419-404c-9d22-77cdb25a7f9f.png">

目前这些链接指向要不是老的，要不是 404

**Comment by linchen1987** [comment]
track in #5637
