### ISSUE TITLE
[Feedback] Send message to specified user 应该覆盖几种基本的消息类型

### ISSUE THREAD

**Issue by wangshijun** [blocklet/blocklet-site#61]
- 比如发送简单的文本、vc、nft、token

---
#### Document Details
* AppId: zNKh7m9JccKmZY8vCSbkdYVoXem5CceAiYD1
* Content: [Communicate with DID Wallet](https://developer.blocklet.io/docs/en/how-to/notification)
* Content Source: [developer/docs/pages/how-to/notification/index.md](https://github.com/blocklet/blocklet-site/tree/main/developer/docs/pages/how-to/notification/index.md)
* Version: 0.1.88

**Comment by wangshijun** [comment]
给钱包发送 vc 时要求了特定的数据结构，没有地方可以知道

**Comment by linchen1987** [comment]
现在文档中有介绍
https://developer.blocklet.io/docs/how-to/notification#message-format
https://developer.blocklet.io/docs/reference/blocklet-sdk#notification-type

再添加几个示例，使开发者通过示例直接 get

**Comment by linchen1987** [comment]
@leermao 已在 https://github.com/blocklet/blocklet-site/pull/79 中添加
