### ISSUE TITLE
[Feedback] prisma 需要 nodejs 14.17+

### ISSUE THREAD

**Issue by donotlb** [blocklet/blocklet-site#75]
这个问题不容易定位, 建议补充到文档里

⚠️ 如果 nodejs 版本低于 14.17, blocklet 日志面板里显示的错误是 "schema.prisma 文件找不到", 需要留意 blocklet server 输出的其它日志

`Error: ENOENT: no such file or directory, open '.../blocklet-server/tmp/.blocklet-server/blocklets/did-comments/0.7.23/schema.prisma'`

![image](https://user-images.githubusercontent.com/24994263/199675158-d9f9895d-c9ab-4a72-ba7a-209583e58061.png)

---
#### Document Details
* AppId: zNKh7m9JccKmZY8vCSbkdYVoXem5CceAiYD1
* Content: [Blocklet Storage](https://developer.blocklet.io/docs/en/how-to/storage#6-deployment-to-the-official-environment)
* Content Source: [developer/docs/pages/how-to/storage/index.md](https://github.com/blocklet/blocklet-site/tree/main/developer/docs/pages/how-to/storage/index.md)
* Version: 0.1.98

**Comment by donotlb** [comment]
相关: https://github.com/ArcBlock/blocklet-server/issues/5733

**Comment by donotlb** [comment]
使用 prisma 的 blocklet 可以在 blocklet.yml 中限制 nodejs version

https://developer.blocklet.io/docs/en/reference/blocklet-spec#specify-the-minimum-nodejs-version-number

**Comment by wangshijun** [comment]
@skypesky 文档请你来更新下吧

**Comment by skypesky** [comment]
@wangshijun  @donotlb 

- 目前在先决条件里面有说明是需要 node.js 在 v14.17 以上，我在哪里再提示一下会更好呢？


<img width="1892" alt="image" src="https://user-images.githubusercontent.com/33124160/199865375-05b409c3-7a6c-4157-911d-dfdf7a6387b3.png">

- 我的理解是： 我在先决条件下面再用一个提示信息。这样 ok 吗？

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/33124160/199867755-1e5fd823-4447-4c89-a3ff-b25e2b9af8ee.png">

**Comment by donotlb** [comment]
可行，或者加一个 FAQ 或常见问题 章节 ?
