### ISSUE TITLE
[Feedback] 文案： Cpu Usage --> CPU Usage

### ISSUE THREAD

**Issue by mave99a** [blocklet/blocklet-site#82]
[Enter feedback here]

文案： Cpu Usage --> CPU Usage

---
#### Document Details
* App Id: zNKaW94r1J9RsYJ7mQZDqN1h9zqNAkQvjG7f
* App Version: 0.3.7
* App Bundle Name: robertmao-com-website
* Page: https://www.robertmao.com/.well-known/service/admin/overview

**Comment by linchen1987** [comment]
https://github.com/ArcBlock/blocklet-server/commit/c7cdb4898efbf9e0abebf02b36e44c66ff9c193e
