### ISSUE TITLE
[Feedback] report issue 里包含了实例的url 可能泄露隐私，带来安全风险

### ISSUE THREAD

**Issue by mave99a** [blocklet/blocklet-site#83]
[Enter feedback here]

例如： * Page: https://www.robertmao.com/.well-known/service/admin/overview

这个在公开issue里，泄漏了我这个实例的细节。 攻击者可能利用。 

---
#### Document Details
* App Id: zNKaW94r1J9RsYJ7mQZDqN1h9zqNAkQvjG7f
* App Version: 0.3.7
* App Bundle Name: robertmao-com-website
* Page: https://www.robertmao.com/.well-known/service/admin/overview

**Comment by linchen1987** [comment]
site 和 path 是排查问题的上下文，应该保留

为了安全：
- 可以把 page 改成 site
- path 做保护，当以 `/.well-known/service` 开头时做转换

**Comment by linchen1987** [comment]
> 当以 /.well-known/service 开头时做转换

感觉不需要转换，`/.well-known` 开头的 url 本来就是公开的

可以把 Document Details 通过 `<!-- -->` 隐藏，不在 issue 中直接显示
